/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college.project;

import javax.swing.JOptionPane;

/**
 *
 * @author Mohamad Sobhy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Students Affairs Management System");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Admin = new javax.swing.JLabel();
        AdminButton = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        UserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atudent Database");
        setLocation(new java.awt.Point(350, 75));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 867));
        jPanel1.setLayout(null);

        Admin.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        Admin.setText("Admin");
        jPanel1.add(Admin);
        Admin.setBounds(352, 473, 66, 33);

        AdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/admin.png"))); // NOI18N
        AdminButton.setToolTipText("Login as an Admin");
        AdminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AdminButton);
        AdminButton.setBounds(253, 242, 264, 264);

        User.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        User.setText("User");
        jPanel1.add(User);
        User.setBounds(858, 473, 66, 44);

        UserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/user-men-tie-256.png"))); // NOI18N
        UserButton.setToolTipText("Login as an User");
        UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserButton.setMaximumSize(new java.awt.Dimension(289, 165));
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UserButton);
        UserButton.setBounds(748, 242, 264, 264);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Welcome to Students Affairs Management System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(176, 33, 957, 43);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/educatione.jpg"))); // NOI18N
        jPanel1.add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1298, 858);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed

        dispose();
        new Login2().setVisible(true);

    }//GEN-LAST:event_AdminButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed

        new report().setVisible(true);
    }//GEN-LAST:event_UserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton AdminButton;
    private javax.swing.JLabel User;
    private javax.swing.JButton UserButton;
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
